### PR TITLE
Update to latest

### PR DESCRIPTION
**Pull request by raymcdermott**
Maybe too latest.

I want to give you the opportunity to review it before I do too much more work.

If you are happy with the direction I will continue.

I decided to make the conversion less literal but can go back if you insist.

### CODE REVIEW

**Comment by shaunlebron** [comment]
Apologies, I wasn't receiving notifications to this repo for some reason.

I'm not sure about maintaining a cljs wrapper for parinfer.js.  I would rather have folks just import it as a js library and interface it with it that way to reduce the surface area of API changes.  The spec stuff is cool though.

what do you think?

**Comment by raymcdermott** [comment]
As you wish. 

I can keep my fork private in that case - no problem.

**Comment by shaunlebron** [comment]
I mean—if you want to maintain it, I can transfer the repo ownership to you.

**Comment by raymcdermott** [comment]
ok - that works

**Comment by shaunlebron** [comment]
I can't transfer the repo to you since you already have parinfer-cljs forked, and it's a name conflict:

screen shot 2018-04-09 at 11 48 08 am

I added you as a collaborator so you can do what you want with this branch here first before removing/renaming your fork to make the transfer possible.

Also, I'll add you to the parinfer-cljs group on clojars so you can publish there:
https://clojars.org/groups/parinfer-cljs

**Comment by raymcdermott** [comment]
I started using the code-mirror ... so not much point in owning this :)

**Pull request closed without merging**
